spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/palco
    username: palco
    password: palco_dev_local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: uma-chave-bem-longa-e-aleatoria-apenas-para-desenvolvimento-local
  expiracao-access-token: 1800000
  expiracao-refresh-token: 604800000